global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'financial-platform'
    environment: 'production'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Backend API metrics
  - job_name: 'backend-api'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Trading Engine metrics
  - job_name: 'trading-engine'
    static_configs:
      - targets: ['trading_engine:8001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Analysis Worker metrics
  - job_name: 'analysis-worker'
    static_configs:
      - targets: ['analysis_worker:8002']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # NVIDIA GPU exporter
  - job_name: 'nvidia-gpu'
    static_configs:
      - targets: ['nvidia-exporter:9835']

  # Blackbox exporter for endpoint monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://backend:8000/api/health
          - http://frontend:80/health
          - http://backend:8000/api/data/market-status
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115